import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
const SPATIAL_DIR = resolve(process.cwd(), "src/components/spatial-canvas");
test("single spatial objects use Map Brief instead of the floating rail", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "useSpatialSelectionRail.tsx"), "utf8");
    assert.match(source, /return null/);
    assert.doesNotMatch(source, /kind === "channel-cluster"/);
    assert.doesNotMatch(source, /kind === "channel"/);
    assert.doesNotMatch(source, /kind === "bot"/);
    assert.doesNotMatch(source, /kind === "widget"/);
    assert.doesNotMatch(source, /kind === "landmark"/);
});
test("channel clusters focus the map instead of opening selection chrome", () => {
    const worldSource = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvasWorld.tsx"), "utf8");
    const markerSource = readFileSync(resolve(SPATIAL_DIR, "ChannelClusterMarker.tsx"), "utf8");
    const canvasSource = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvas.tsx"), "utf8");
    const navigationSource = readFileSync(resolve(SPATIAL_DIR, "useSpatialNavigation.tsx"), "utf8");
    const clusteringSource = readFileSync(resolve(SPATIAL_DIR, "spatialClustering.ts"), "utf8");
    assert.match(clusteringSource, /CHANNEL_CLUSTER_FOCUS_SCALE = CHANNEL_CLUSTER_EXIT_SCALE \+ 0\.05/);
    assert.doesNotMatch(worldSource, /0\.42/);
    assert.match(navigationSource, /const CLUSTER_FOCUS_MS = 520/);
    assert.match(navigationSource, /animateCameraTo\(\{/);
    assert.match(worldSource, /CHANNEL_CLUSTER_FOCUS_SCALE/);
    assert.match(worldSource, /flyToWorldBounds\(cluster\.worldBounds, CHANNEL_CLUSTER_FOCUS_SCALE, CHANNEL_CLUSTER_FOCUS_SCALE\)/);
    assert.match(worldSource, /setClusterFocusNodeIds/);
    assert.match(worldSource, /data-spatial-cluster-focus-cue/);
    assert.match(navigationSource, /maxScale = 0\.62/);
    assert.match(navigationSource, /Math\.min\(\s*maxScale,/);
    assert.match(worldSource, /setSelectedSpatialObject\(null\)/);
    assert.match(canvasSource, /flyToWorldBounds=\{flyToWorldBounds\}/);
    assert.doesNotMatch(worldSource, /onDiveWinner/);
    assert.doesNotMatch(worldSource, /diveToChannel\(cluster\.winner\.channel\.id/);
    assert.doesNotMatch(markerSource, /onDiveWinner/);
    assert.match(markerSource, /focusPrimaryCluster/);
    assert.match(markerSource, /onPointerDown=\{focusPrimaryCluster\}/);
    assert.match(markerSource, /onMouseDown=\{focusPrimaryCluster\}/);
    assert.match(markerSource, /onDoubleClick=\{focusPrimaryCluster\}/);
    assert.doesNotMatch(canvasSource, /kind: "channel-cluster"/);
});
test("cluster overview suppresses the focus lens hint", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvasOverlays.tsx"), "utf8");
    assert.doesNotMatch(source, /LensHint/);
});
test("attention signal keeps the ring visual-only and makes only the badge clickable", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "SpatialAttentionLayer.tsx"), "utf8");
    assert.match(source, /pointer-events-none absolute left-1\/2 top-1\/2/);
    assert.match(source, /aria-hidden/);
    assert.match(source, /pointer-events-auto absolute -right-1 -top-1/);
    assert.match(source, /<AlertTriangle size=\{12\}/);
});
test("Map Brief jump frames targets left of an open Starboard panel", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "useSpatialNavigation.tsx"), "utf8");
    assert.match(source, /spatialVisibleCenterX/);
    assert.match(source, /querySelector\("\[data-starboard-panel='true'\]"\)/);
    assert.match(source, /panelRect\?\.left/);
    assert.match(source, /rect\.left/);
});
test("Map Brief object rows reveal targets with animated camera movement", () => {
    const navigationSource = readFileSync(resolve(SPATIAL_DIR, "useSpatialNavigation.tsx"), "utf8");
    const chromeSource = readFileSync(resolve(SPATIAL_DIR, "UsageDensityChrome.tsx"), "utf8");
    assert.match(navigationSource, /const OBJECT_REVEAL_MS = 460/);
    assert.match(navigationSource, /flyToStarboardObject[\s\S]*animateCameraTo\(\{ x: targetX, y: targetY, scale: targetScale \}, OBJECT_REVEAL_MS\)/);
    assert.match(navigationSource, /flyToWorldPoint[\s\S]*animateCameraTo\(\{ x: targetX, y: targetY, scale: targetScale \}, OBJECT_REVEAL_MS\)/);
    assert.match(chromeSource, /const handleObjectClick = \(item: StarboardObjectItem\) => \{\s*item\.onSelect\(\);\s*\};/);
    assert.doesNotMatch(chromeSource, /objectClickTimerRef/);
});
test("cluster focus can recover viewport metrics before flying bounds", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "useSpatialNavigation.tsx"), "utf8");
    assert.match(source, /querySelector\('\[data-spatial-canvas="true"\]'\)/);
    assert.match(source, /getBoundingClientRect\(\)/);
    assert.match(source, /viewportRectRef\.current = rect/);
});
test("selected objects get a world anchor and suppress competing hover cards", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvasWorld.tsx"), "utf8");
    assert.match(source, /data-spatial-selected-anchor/);
    assert.match(source, /showLabel: false/);
    assert.match(source, /showLabel: true/);
    assert.match(source, /data-spatial-selected-anchor-label/);
    assert.match(source, /SelectedObjectAnchor/);
    assert.match(source, /ring-1 ring-accent\/38 ring-offset-2/);
    assert.match(source, /!starboardOpen \|\| !selectedSpatialObject/);
    assert.match(source, /!channelClusterMode/);
    assert.match(source, /interactiveZoom >= 0\.65/);
    assert.match(source, /setTimeout\(\(\) => setHoverCardNodeId/);
});
test("Map Brief selected object uses quiet triage instead of side-stripe chrome", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "UsageDensityChrome.tsx"), "utf8");
    assert.match(source, /data-brief-tone=\{tone\}/);
    assert.match(source, /SelectedObjectMetaChips/);
    assert.match(source, /selectedInspectorToneClass/);
    assert.match(source, /label: "Investigate"/);
    assert.match(source, /label: "Next up"/);
    assert.match(source, /label: "Recently changed"/);
    assert.match(source, /mapCueIntent/);
    assert.doesNotMatch(source, /border-l-2/);
    assert.doesNotMatch(source, /border-l-danger/);
    assert.doesNotMatch(source, /border-l-warning/);
    assert.doesNotMatch(source, /border-l-accent/);
});
test("Map Brief active attention is actionable without opening the Attention panel first", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "UsageDensityChrome.tsx"), "utf8");
    assert.match(source, /findActiveAttentionItemsForObject/);
    assert.match(source, /data-testid="map-brief-attention-actions"/);
    assert.match(source, /attentionDeckHref/);
    assert.match(source, /Review finding/);
    assert.match(source, /Review raw signal/);
    assert.match(source, /operator-reviewed finding/);
    assert.match(source, /attentionPrimaryActionLabel/);
    assert.doesNotMatch(source, /Acknowledge target/);
    assert.doesNotMatch(source, /Open in Attention/);
});
test("clusters surface aggregate actionable cues without opening selection chrome", () => {
    const worldSource = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvasWorld.tsx"), "utf8");
    const markerSource = readFileSync(resolve(SPATIAL_DIR, "ChannelClusterMarker.tsx"), "utf8");
    assert.match(worldSource, /clusterCueSummary/);
    assert.match(worldSource, /to inspect/);
    assert.match(worldSource, /cueSummary=\{clusterCueSummary\(cluster, mapState\)\}/);
    assert.match(markerSource, /cueSummary/);
    assert.match(markerSource, /near \$\{channelName\(cluster\)\}/);
});
test("spatial glanceability uses shared cue markers and compass without side stripes", () => {
    const cueSource = readFileSync(resolve(SPATIAL_DIR, "SpatialActionCues.tsx"), "utf8");
    const worldSource = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvasWorld.tsx"), "utf8");
    const overlaySource = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvasOverlays.tsx"), "utf8");
    const modelSource = readFileSync(resolve(SPATIAL_DIR, "useSpatialStarboardModels.tsx"), "utf8");
    const routerSource = readFileSync(resolve(process.cwd(), "src/router.tsx"), "utf8");
    assert.match(cueSource, /data-testid="spatial-action-cue-marker"/);
    assert.match(cueSource, /pointer-events-auto/);
    assert.match(cueSource, /item\.onSelect\(\)/);
    assert.match(cueSource, /data-testid="spatial-action-compass"/);
    assert.match(cueSource, /data-spatial-action-compass-collapsed/);
    assert.match(cueSource, /topActionCompassItems/);
    assert.match(cueSource, /Next actions/);
    assert.match(cueSource, /Best review targets from live map state/);
    assert.match(cueSource, /data-spatial-action-compass-selected/);
    assert.match(cueSource, /cueCountLabel/);
    assert.match(cueSource, /selectedItem/);
    assert.match(cueSource, /rankedItems\.filter\(\(item\) => item\.id !== selectedItem\.id\)/);
    assert.match(overlaySource, /collapsed=\{Boolean\(starboardOpen && selectedStarboardObject\)\}/);
    assert.match(worldSource, /<SpatialActionCueLayer/);
    assert.match(overlaySource, /<ActionCompass/);
    assert.match(modelSource, /worldW: node\.world_w/);
    assert.match(modelSource, /worldH: node\.world_h/);
    assert.match(modelSource, /attentionReviewHref/);
    assert.match(modelSource, /Review signal/);
    assert.match(modelSource, /attentionDeckHref\(\{ itemId: direct\.id \}\)/);
    assert.match(routerSource, /const HubAttentionPage = lazy/);
    assert.match(routerSource, /\{ path: "hub\/attention", element: <HubAttentionPage \/> \}/);
    assert.doesNotMatch(cueSource, /data-spatial-action-cue-halo/);
    assert.doesNotMatch(cueSource, /border-l-/);
    assert.doesNotMatch(cueSource, /animate-/);
});
test("Map Brief warning lines expose concrete review targets", () => {
    const chromeSource = readFileSync(resolve(SPATIAL_DIR, "UsageDensityChrome.tsx"), "utf8");
    const typeSource = readFileSync(resolve(process.cwd(), "src/api/types/workspaceMapState.ts"), "utf8");
    assert.match(chromeSource, /data-testid="map-brief-signal-action"/);
    assert.match(chromeSource, /Review signal/);
    assert.match(chromeSource, /Review finding/);
    assert.match(chromeSource, /Open trace/);
    assert.match(chromeSource, /Open automation/);
    assert.match(chromeSource, /openTraceInspector/);
    assert.match(chromeSource, /signal\.correlation_id/);
    assert.match(typeSource, /correlation_id\?: string \| null/);
});
test("Attention operator sweep is global and normal assignment hides the operator bot", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "SpatialAttentionLayer.tsx"), "utf8");
    const modelSource = readFileSync(resolve(SPATIAL_DIR, "SpatialAttentionModel.ts"), "utf8");
    assert.match(modelSource, /OPERATOR_BOT_ID = "orchestrator"/);
    assert.match(modelSource, /getAttentionWorkflowState/);
    assert.match(modelSource, /attentionBucketSummary/);
    assert.match(modelSource, /operator_review/);
    assert.match(modelSource, /isAttentionSweepCandidate/);
    assert.match(source, /Operator sweep/);
    assert.match(source, /Runs across untriaged issues, not just the selected target/);
    assert.match(source, /Model override/);
    assert.match(source, /Start sweep/);
    assert.match(source, /setOperatorRunOpen\(true\)/);
    assert.match(source, /useAttentionTriageRuns/);
    assert.match(source, /Starting operator sweep/);
    assert.match(source, /Creating the run and transcript/);
    assert.match(source, /Still waiting for the server/);
    assert.match(source, /out of DB connections/);
    assert.match(source, /Back to sweep setup/);
    assert.match(source, /Operator history/);
    assert.match(source, /OperatorReviewOverview/);
    assert.match(source, /Open run/);
    assert.match(source, /attentionBucketSummary\(grouped\)/);
    assert.match(source, /<OperatorTriageRunPanel run=\{run\}/);
    assert.match(source, /surface="operator-panel"/);
    assert.match(source, /min-h-\[min\(76vh,760px\)\]/);
    assert.match(source, /id="operator-review-findings"/);
    assert.doesNotMatch(source, /h-\[min\(62vh,640px\)\] min-h-\[420px\]/);
    assert.match(source, /Operator Review/);
    assert.match(source, /Evidence/);
    assert.match(source, /Review these findings/);
    assert.match(source, /cleared by Operator/);
    assert.match(source, /recoveredTriageRun/);
    assert.match(source, /visibleTriageRun/);
    assert.match(source, /getOperatorTriage\(item\)/);
    assert.match(source, /Ready for review/);
    assert.match(source, /Processed by operator/);
    assert.match(source, /bots\.filter\(\(bot\) => bot\.id !== OPERATOR_BOT_ID\)/);
    assert.match(source, /Send this issue to a bot/);
    assert.match(source, /Optional follow-up for issue \{currentIndex \+ 1\}/);
    assert.match(source, /Operator sweep handles the whole queue/);
    assert.match(source, /bots=\{assignableBots\}/);
    assert.match(source, /Accepting trains future sweeps/);
    assert.match(source, /Accept finding/);
    assert.match(source, /Acknowledge/);
    assert.match(source, /Resolve/);
    assert.match(source, /Mark wrong/);
    assert.match(source, /Change routing/);
    assert.match(source, /operatorRouteLabel/);
    assert.doesNotMatch(source, /Route to dev/);
    assert.doesNotMatch(source, />Confirm</);
});
test("Operator sweep transcript uses a full-width chat surface instead of a nested card", () => {
    const attentionSource = readFileSync(resolve(SPATIAL_DIR, "SpatialAttentionLayer.tsx"), "utf8");
    const sessionSource = readFileSync(resolve(process.cwd(), "src/components/chat/SessionChatView.tsx"), "utf8");
    const areaSource = readFileSync(resolve(process.cwd(), "src/components/chat/ChatMessageArea.tsx"), "utf8");
    const cssSource = readFileSync(resolve(process.cwd(), "global.css"), "utf8");
    assert.match(attentionSource, /surface="operator-panel"/);
    assert.match(sessionSource, /surface\?: "default" \| "operator-panel"/);
    assert.match(sessionSource, /compact=\{compactMessages\}/);
    assert.match(sessionSource, /contentMaxWidthOverride=\{surface === "operator-panel" \? "none" : undefined\}/);
    assert.match(areaSource, /data-chat-surface=\{surface\}/);
    assert.match(areaSource, /chat-message-area-operator-panel/);
    assert.match(cssSource, /\.chat-message-area-operator-panel pre/);
    assert.match(cssSource, /overflow-wrap: anywhere/);
    assert.match(cssSource, /overflow-x: hidden/);
    assert.doesNotMatch(attentionSource, /rounded-md bg-surface-raised\/70/);
});
test("Starboard attention station is only a launcher for Mission Control Review", () => {
    const chromeSource = readFileSync(resolve(SPATIAL_DIR, "UsageDensityChrome.tsx"), "utf8");
    const deckSource = readFileSync(resolve(process.cwd(), "src/components/attention/AttentionCommandDeck.tsx"), "utf8");
    const rootSource = readFileSync(resolve(process.cwd(), "src/layouts/RootLayout.tsx"), "utf8");
    const hubPageSource = readFileSync(resolve(process.cwd(), "app/(app)/hub/attention.tsx"), "utf8");
    const commandCenterSource = readFileSync(resolve(process.cwd(), "app/(app)/hub/command-center.tsx"), "utf8");
    const channelHeaderSource = readFileSync(resolve(process.cwd(), "app/(app)/channels/[channelId]/ChannelHeader.tsx"), "utf8");
    assert.match(chromeSource, /AttentionStarboardSummary/);
    assert.match(chromeSource, /data-testid="starboard-attention-summary"/);
    assert.match(chromeSource, /Open Review/);
    assert.match(chromeSource, /attentionDeckHref/);
    assert.doesNotMatch(chromeSource, /Open deck/);
    assert.doesNotMatch(chromeSource, /Open Command Deck/);
    assert.doesNotMatch(chromeSource, /<AttentionHubContent/);
    assert.doesNotMatch(rootSource, /AttentionHubDrawerRoot/);
    assert.match(hubPageSource, /requestedChannelId/);
    assert.match(hubPageSource, /requestedMode/);
    assert.match(hubPageSource, /requestedRunId/);
    assert.match(hubPageSource, /onRunSelect/);
    assert.match(hubPageSource, /requestedTargetKind/);
    assert.match(commandCenterSource, /Navigate/);
    assert.match(commandCenterSource, /attentionDeckHref/);
    assert.match(channelHeaderSource, /attentionDeckHref\(\{ channelId, mode: "inbox" \}\)/);
    assert.match(deckSource, /Mission Control Review/);
    assert.match(deckSource, /Recommended/);
    assert.match(deckSource, /Run Operator sweep/);
    assert.match(deckSource, /Raw signals waiting/);
    assert.match(deckSource, /selectedRunId/);
    assert.match(deckSource, /onRunSelect/);
    assert.match(deckSource, /Transcript evidence/);
    assert.match(deckSource, /runModePinned/);
    assert.match(deckSource, /sweepBusy/);
    assert.match(deckSource, /onSelect\(null\);\n    setDeckMode\("runs"\)/);
    assert.match(deckSource, /Run log/);
    assert.match(deckSource, /RunReceipt/);
    assert.match(deckSource, /attention-run-receipt/);
    assert.match(deckSource, />Transcript</);
    assert.match(deckSource, /Send this issue to a bot/);
    assert.match(deckSource, /<details/);
});
