import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
const SPATIAL_DIR = resolve(process.cwd(), "src/components/spatial-canvas");
test("single spatial objects use Map Brief instead of the floating rail", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "useSpatialSelectionRail.tsx"), "utf8");
    assert.match(source, /return null/);
    assert.doesNotMatch(source, /kind === "channel-cluster"/);
    assert.doesNotMatch(source, /kind === "channel"/);
    assert.doesNotMatch(source, /kind === "bot"/);
    assert.doesNotMatch(source, /kind === "widget"/);
    assert.doesNotMatch(source, /kind === "landmark"/);
});
test("channel clusters focus the map instead of opening selection chrome", () => {
    const worldSource = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvasWorld.tsx"), "utf8");
    const markerSource = readFileSync(resolve(SPATIAL_DIR, "ChannelClusterMarker.tsx"), "utf8");
    const canvasSource = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvas.tsx"), "utf8");
    const navigationSource = readFileSync(resolve(SPATIAL_DIR, "useSpatialNavigation.tsx"), "utf8");
    const clusteringSource = readFileSync(resolve(SPATIAL_DIR, "spatialClustering.ts"), "utf8");
    assert.match(clusteringSource, /CHANNEL_CLUSTER_FOCUS_SCALE = CHANNEL_CLUSTER_EXIT_SCALE \+ 0\.05/);
    assert.doesNotMatch(worldSource, /0\.42/);
    assert.match(navigationSource, /const CLUSTER_FOCUS_MS = 520/);
    assert.match(navigationSource, /animateCameraTo\(\{/);
    assert.match(worldSource, /CHANNEL_CLUSTER_FOCUS_SCALE/);
    assert.match(worldSource, /flyToWorldBounds\(cluster\.worldBounds, CHANNEL_CLUSTER_FOCUS_SCALE, CHANNEL_CLUSTER_FOCUS_SCALE\)/);
    assert.match(worldSource, /setClusterFocusNodeIds/);
    assert.match(worldSource, /data-spatial-cluster-focus-cue/);
    assert.match(navigationSource, /maxScale = 0\.62/);
    assert.match(navigationSource, /Math\.min\(\s*maxScale,/);
    assert.match(worldSource, /setSelectedSpatialObject\(null\)/);
    assert.match(canvasSource, /flyToWorldBounds=\{flyToWorldBounds\}/);
    assert.doesNotMatch(worldSource, /onDiveWinner/);
    assert.doesNotMatch(worldSource, /diveToChannel\(cluster\.winner\.channel\.id/);
    assert.doesNotMatch(markerSource, /onDiveWinner/);
    assert.match(markerSource, /focusPrimaryCluster/);
    assert.match(markerSource, /onPointerDown=\{focusPrimaryCluster\}/);
    assert.match(markerSource, /onMouseDown=\{focusPrimaryCluster\}/);
    assert.match(markerSource, /onDoubleClick=\{focusPrimaryCluster\}/);
    assert.doesNotMatch(canvasSource, /kind: "channel-cluster"/);
});
test("cluster overview suppresses the focus lens hint", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvasOverlays.tsx"), "utf8");
    assert.doesNotMatch(source, /LensHint/);
});
test("attention signal keeps the ring visual-only and makes only the badge clickable", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "SpatialAttentionLayer.tsx"), "utf8");
    assert.match(source, /pointer-events-none absolute left-1\/2 top-1\/2/);
    assert.match(source, /aria-hidden/);
    assert.match(source, /pointer-events-auto absolute -right-1 -top-1/);
    assert.match(source, /<AlertTriangle size=\{12\}/);
});
test("Map Brief jump frames targets left of an open Starboard panel", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "useSpatialNavigation.tsx"), "utf8");
    assert.match(source, /spatialVisibleCenterX/);
    assert.match(source, /querySelector\("\[data-starboard-panel='true'\]"\)/);
    assert.match(source, /panelRect\?\.left/);
    assert.match(source, /rect\.left/);
});
test("Map Brief object rows reveal targets with animated camera movement", () => {
    const navigationSource = readFileSync(resolve(SPATIAL_DIR, "useSpatialNavigation.tsx"), "utf8");
    const chromeSource = readFileSync(resolve(SPATIAL_DIR, "UsageDensityChrome.tsx"), "utf8");
    assert.match(navigationSource, /const OBJECT_REVEAL_MS = 460/);
    assert.match(navigationSource, /flyToStarboardObject[\s\S]*animateCameraTo\(\{ x: targetX, y: targetY, scale: targetScale \}, OBJECT_REVEAL_MS\)/);
    assert.match(navigationSource, /flyToWorldPoint[\s\S]*animateCameraTo\(\{ x: targetX, y: targetY, scale: targetScale \}, OBJECT_REVEAL_MS\)/);
    assert.match(chromeSource, /const handleObjectClick = \(item: StarboardObjectItem\) => \{\s*item\.onSelect\(\);\s*\};/);
    assert.doesNotMatch(chromeSource, /objectClickTimerRef/);
});
test("cluster focus can recover viewport metrics before flying bounds", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "useSpatialNavigation.tsx"), "utf8");
    assert.match(source, /querySelector\('\[data-spatial-canvas="true"\]'\)/);
    assert.match(source, /getBoundingClientRect\(\)/);
    assert.match(source, /viewportRectRef\.current = rect/);
});
test("selected objects get a world anchor and suppress competing hover cards", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvasWorld.tsx"), "utf8");
    assert.match(source, /data-spatial-selected-anchor/);
    assert.match(source, /showLabel: false/);
    assert.match(source, /showLabel: true/);
    assert.match(source, /data-spatial-selected-anchor-label/);
    assert.match(source, /SelectedObjectAnchor/);
    assert.match(source, /ring-1 ring-accent\/38 ring-offset-2/);
    assert.match(source, /!starboardOpen \|\| !selectedSpatialObject/);
    assert.match(source, /!channelClusterMode/);
    assert.match(source, /interactiveZoom >= 0\.65/);
    assert.match(source, /setTimeout\(\(\) => setHoverCardNodeId/);
});
test("Map Brief selected object uses quiet triage instead of side-stripe chrome", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "UsageDensityChrome.tsx"), "utf8");
    assert.match(source, /data-brief-tone=\{tone\}/);
    assert.match(source, /SelectedObjectMetaChips/);
    assert.match(source, /selectedInspectorToneClass/);
    assert.match(source, /label: "Investigate"/);
    assert.match(source, /label: "Next up"/);
    assert.match(source, /label: "Recently changed"/);
    assert.match(source, /mapCueIntent/);
    assert.doesNotMatch(source, /border-l-2/);
    assert.doesNotMatch(source, /border-l-danger/);
    assert.doesNotMatch(source, /border-l-warning/);
    assert.doesNotMatch(source, /border-l-accent/);
});
test("Map Brief active attention is actionable without opening the Attention panel first", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "UsageDensityChrome.tsx"), "utf8");
    assert.match(source, /useBulkAcknowledgeAttentionItems/);
    assert.match(source, /WORKSPACE_MAP_STATE_KEY/);
    assert.match(source, /findActiveAttentionItemsForObject/);
    assert.match(source, /data-testid="map-brief-attention-actions"/);
    assert.match(source, /Acknowledge target/);
    assert.match(source, /scope:\s*"target"/);
    assert.match(source, /Open in Attention/);
    assert.match(source, /label: "Review issue"/);
});
test("clusters surface aggregate actionable cues without opening selection chrome", () => {
    const worldSource = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvasWorld.tsx"), "utf8");
    const markerSource = readFileSync(resolve(SPATIAL_DIR, "ChannelClusterMarker.tsx"), "utf8");
    assert.match(worldSource, /clusterCueSummary/);
    assert.match(worldSource, /to inspect/);
    assert.match(worldSource, /cueSummary=\{clusterCueSummary\(cluster, mapState\)\}/);
    assert.match(markerSource, /cueSummary/);
    assert.match(markerSource, /near \$\{channelName\(cluster\)\}/);
});
test("spatial glanceability uses shared cue markers and compass without side stripes", () => {
    const cueSource = readFileSync(resolve(SPATIAL_DIR, "SpatialActionCues.tsx"), "utf8");
    const worldSource = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvasWorld.tsx"), "utf8");
    const overlaySource = readFileSync(resolve(SPATIAL_DIR, "SpatialCanvasOverlays.tsx"), "utf8");
    const modelSource = readFileSync(resolve(SPATIAL_DIR, "useSpatialStarboardModels.tsx"), "utf8");
    assert.match(cueSource, /data-testid="spatial-action-cue-marker"/);
    assert.match(cueSource, /data-testid="spatial-action-compass"/);
    assert.match(cueSource, /data-spatial-action-compass-collapsed/);
    assert.match(cueSource, /topActionCompassItems/);
    assert.match(cueSource, /Needs action/);
    assert.match(cueSource, /Best next clicks from live map state/);
    assert.match(cueSource, /data-spatial-action-compass-selected/);
    assert.match(cueSource, /cueCountLabel/);
    assert.match(cueSource, /selectedItem/);
    assert.match(cueSource, /rankedItems\.filter\(\(item\) => item\.id !== selectedItem\.id\)/);
    assert.match(overlaySource, /collapsed=\{Boolean\(starboardOpen && selectedStarboardObject\)\}/);
    assert.match(worldSource, /<SpatialActionCueLayer/);
    assert.match(overlaySource, /<ActionCompass/);
    assert.match(modelSource, /worldW: node\.world_w/);
    assert.match(modelSource, /worldH: node\.world_h/);
    assert.doesNotMatch(cueSource, /data-spatial-action-cue-halo/);
    assert.doesNotMatch(cueSource, /border-l-/);
    assert.doesNotMatch(cueSource, /animate-/);
});
test("Map Brief warning lines expose concrete review targets", () => {
    const chromeSource = readFileSync(resolve(SPATIAL_DIR, "UsageDensityChrome.tsx"), "utf8");
    const typeSource = readFileSync(resolve(process.cwd(), "src/api/types/workspaceMapState.ts"), "utf8");
    assert.match(chromeSource, /data-testid="map-brief-signal-action"/);
    assert.match(chromeSource, /Review in Attention/);
    assert.match(chromeSource, /Open trace/);
    assert.match(chromeSource, /Open automation/);
    assert.match(chromeSource, /openTraceInspector/);
    assert.match(chromeSource, /signal\.correlation_id/);
    assert.match(typeSource, /correlation_id\?: string \| null/);
});
test("Attention operator sweep is global and normal assignment hides the operator bot", () => {
    const source = readFileSync(resolve(SPATIAL_DIR, "SpatialAttentionLayer.tsx"), "utf8");
    assert.match(source, /const OPERATOR_BOT_ID = "orchestrator"/);
    assert.match(source, /Operator sweep/);
    assert.match(source, /Runs across all active issues, not just the selected target/);
    assert.match(source, /Model override/);
    assert.match(source, /Start sweep/);
    assert.match(source, /setOperatorRunOpen\(true\)/);
    assert.match(source, /useAttentionTriageRuns/);
    assert.match(source, /Starting operator sweep/);
    assert.match(source, /Creating the run and transcript/);
    assert.match(source, /Still waiting for the server/);
    assert.match(source, /out of DB connections/);
    assert.match(source, /Back to sweep setup/);
    assert.match(source, /Operator history/);
    assert.match(source, /recoveredTriageRun/);
    assert.match(source, /visibleTriageRun/);
    assert.match(source, /getOperatorTriage\(item\)/);
    assert.match(source, /Ready for review/);
    assert.match(source, /Processed by operator/);
    assert.match(source, /bots\.filter\(\(bot\) => bot\.id !== OPERATOR_BOT_ID\)/);
    assert.match(source, /Assign current issue/);
    assert.match(source, /Only sends issue \{currentIndex \+ 1\} to a normal bot/);
    assert.match(source, /bots=\{assignableBots\}/);
    assert.match(source, /Accepting trains future sweeps/);
    assert.match(source, /Accept finding/);
    assert.match(source, /Acknowledge/);
    assert.match(source, /Resolve/);
    assert.match(source, /Mark wrong/);
    assert.match(source, /Change routing/);
    assert.match(source, /operatorRouteLabel/);
    assert.doesNotMatch(source, /Route to dev/);
    assert.doesNotMatch(source, />Confirm</);
});
