export const CHAT_ROW_AVATAR_SIZE = 36;
export const CHAT_ROW_GAP = 12;
export const CHAT_ROW_X_PADDING = 20;
export const CHAT_ROW_NARROW_X_PADDING = 12;
export const CHAT_ROW_TERMINAL_X_PADDING = 12;

export const CHAT_ROW_CONTENT_INDENT = CHAT_ROW_X_PADDING + CHAT_ROW_AVATAR_SIZE + CHAT_ROW_GAP;
