use_default_settings: true

search:
  formats:
    - html
    - json

server:
  # IMPORTANT: Change this to a unique random string in production
  secret_key: "change-me-to-a-random-secret"
  limiter: false
