// Friendly re-exports over the auto-generated OpenAPI types.
//
// `api.generated.ts` is regenerated by `scripts/generate-api-types.sh` from
// the live FastAPI route table; CI's `api-type-drift` job fails if it lags.
// This shim narrows the verbose `components["schemas"]["X"]` form down to a
// single import and gives us one place to alias if a generated name is awkward.
//
// Migration is per-feature: replace imports from `./api` with imports from
// here; once nothing imports the legacy hand-written types, that file can go.

import type { components, operations, paths } from "./api.generated";

export type Schema = components["schemas"];
export type Paths = paths;
export type Operations = operations;

// Convenience re-exports for the most-used schemas.
// Add to this list as feature-by-feature migration adopts generated types.
export type ChannelOut = Schema["ChannelOut"];
export type ChannelBotMemberOut = Schema["ChannelBotMemberOut"];
export type ProjectCodingRunOut = Schema["ProjectCodingRunOut"];
