"""Standardize task tracking format across all workspace schema templates.

Appends kanban-style tasks.md guidance to templates that lack it,
and renames 'Mission Control' template to 'Structured Task Hub'.

Revision ID: 127
Revises: 126
"""

from alembic import op
import sqlalchemy as sa


revision = "127"
down_revision = "126"


_TASK_TRACKING_GUIDANCE = (
    "\n\n### Task Tracking Format\n\n"
    "Use kanban-style columns and structured cards in **tasks.md**:\n\n"
    "    ## Backlog\n"
    "    ### Task title\n"
    "    - **id**: mc-XXXXXX (auto-generated by create_task_card tool)\n"
    "    - **priority**: low | medium | high | critical\n"
    "    - **created**: YYYY-MM-DD\n"
    "    - **assigned**: bot-name or person\n"
    "    - **tags**: comma-separated\n"
    "    - **due**: YYYY-MM-DD\n\n"
    "    Free-text description here.\n\n"
    "    ## In Progress\n"
    "    ## Review\n"
    "    ## Done\n\n"
    "Use `create_task_card` and `move_task_card` tools for automated task management.\n"
    "Custom columns are supported — add any `## Column Name` header."
)

# Per-template adjustments: (template_id, extra_guidance_prepended_to_standard)
# These are appended AFTER the standard _TASK_TRACKING_GUIDANCE
_PER_TEMPLATE_EXTRAS = {
    # Research — suggest domain-specific columns
    "a0000000-0000-0000-0000-000000000002": (
        "\nSuggested columns for research: Backlog, Investigating, Writing, Done."
    ),
    # Creative — suggest domain-specific columns
    "a0000000-0000-0000-0000-000000000003": (
        "\nSuggested columns for creative work: Ideas, In Progress, Feedback, Done."
    ),
    # PM Hub — note coexistence with actions.md
    "a0000000-0000-0000-0000-000000000005": (
        "\nUse tasks.md for kanban-style task tracking. "
        "Keep actions.md for cross-project action items and escalations."
    ),
    # QA — note coexistence with bugs.md and test-cases.md
    "a0000000-0000-0000-0000-000000000007": (
        "\nUse tasks.md for general task tracking. "
        "Keep bugs.md and test-cases.md for domain-specific tracking."
    ),
}

# Templates to update (all 7). Mission Control (006) already has task guidance
# so we skip appending the standard block to it, but we DO rename it.
_TEMPLATES_TO_UPDATE = [
    "a0000000-0000-0000-0000-000000000001",  # Software Development
    "a0000000-0000-0000-0000-000000000002",  # Research / Analysis
    "a0000000-0000-0000-0000-000000000003",  # Creative Project
    "a0000000-0000-0000-0000-000000000004",  # General Project
    "a0000000-0000-0000-0000-000000000005",  # Project Management Hub
    # "a0000000-0000-0000-0000-000000000006" — Mission Control: already has task guidance
    "a0000000-0000-0000-0000-000000000007",  # Software Testing / QA
]


def upgrade() -> None:
    # 1. Append standardized task tracking guidance to templates that lack it
    for template_id in _TEMPLATES_TO_UPDATE:
        extra = _PER_TEMPLATE_EXTRAS.get(template_id, "")
        suffix = _TASK_TRACKING_GUIDANCE + extra
        op.execute(
            sa.text(
                "UPDATE prompt_templates "
                "SET content = content || :suffix "
                "WHERE id = CAST(:id AS uuid) "
                "AND content NOT LIKE '%create_task_card%'"
            ).bindparams(id=template_id, suffix=suffix)
        )

    # 2. Rename Mission Control template to Structured Task Hub
    op.execute(
        sa.text(
            "UPDATE prompt_templates "
            "SET name = 'Structured Task Hub' "
            "WHERE id = CAST(:id AS uuid)"
        ).bindparams(id="a0000000-0000-0000-0000-000000000006")
    )


def downgrade() -> None:
    # Revert template name
    op.execute(
        sa.text(
            "UPDATE prompt_templates "
            "SET name = 'Mission Control' "
            "WHERE id = CAST(:id AS uuid)"
        ).bindparams(id="a0000000-0000-0000-0000-000000000006")
    )
    # Note: we don't strip the appended task guidance — it's safe to leave
