import {
  Bot,
  Plug,
  Monitor,
  Server,
  Cable,
  Wrench,
  BookOpen,
  FileText,
  Paperclip,
  Boxes,
  ClipboardList,
  Lock,
  Shield,
  ShieldCheck,
  Key,
  Webhook,
  FileCode,
  BarChart3,
  Activity,
  Users,
  ScrollText,
  HardDrive,
  Code2,
  Brain,
  Settings,
  MessageCircle,
  Zap,
} from "lucide-react";
import type { PaletteItem } from "./types";

export const ADMIN_ITEMS: PaletteItem[] = [
  // -- Configure --
  { id: "nav-bots", label: "Bots", href: "/admin/bots", icon: Bot, category: "Configure" },
  { id: "nav-integrations", label: "Integrations", href: "/admin/integrations", icon: Plug, category: "Configure" },
  { id: "nav-machines", label: "Machines", href: "/admin/machines", icon: Monitor, category: "Configure" },
  { id: "nav-providers", label: "Providers", href: "/admin/providers", icon: Server, category: "Configure" },
  { id: "nav-mcp", label: "MCP Servers", href: "/admin/mcp-servers", icon: Cable, category: "Configure" },
  { id: "nav-tools", label: "Tools", href: "/admin/tools", icon: Wrench, category: "Configure" },
  { id: "nav-skills", label: "Skills", href: "/admin/skills", icon: BookOpen, category: "Configure" },
  { id: "nav-templates", label: "Templates", href: "/admin/prompt-templates", icon: FileText, category: "Configure" },
  { id: "nav-attachments", label: "Attachments", href: "/admin/attachments", icon: Paperclip, category: "Configure" },
  { id: "nav-docker", label: "Docker Stacks", href: "/admin/docker-stacks", icon: Boxes, category: "Configure" },
  // -- Automate --
  { id: "nav-learning", label: "Memory & Knowledge", href: "/admin/learning", icon: Brain, category: "Automate" },
  { id: "nav-learning-overview", label: "Memory & Knowledge: Overview", hint: "Memory & Knowledge", href: "/admin/learning#Overview", icon: Brain, category: "Automate" },
  { id: "nav-learning-memory", label: "Memory & Knowledge: Memory", hint: "Memory & Knowledge", href: "/admin/learning#Memory", icon: Brain, category: "Automate" },
  { id: "nav-learning-knowledge", label: "Memory & Knowledge: Knowledge", hint: "Memory & Knowledge", href: "/admin/learning#Knowledge", icon: Brain, category: "Automate" },
  { id: "nav-learning-history", label: "Memory & Knowledge: History", hint: "Memory & Knowledge", href: "/admin/learning#History", icon: Brain, category: "Automate" },
  { id: "nav-learning-dreaming", label: "Memory & Knowledge: Dreaming", hint: "Memory & Knowledge", href: "/admin/learning#Dreaming", icon: Brain, category: "Automate" },
  { id: "nav-learning-skills", label: "Memory & Knowledge: Skills", hint: "Memory & Knowledge", href: "/admin/learning#Skills", icon: Brain, category: "Automate" },
  { id: "nav-tasks", label: "Automations", href: "/admin/automations", icon: ClipboardList, category: "Automate" },
  { id: "nav-workflows", label: "Workflows", href: "/admin/workflows", icon: Zap, category: "Automate" },
  // -- Security --
  { id: "nav-secrets", label: "Secrets", href: "/admin/secret-values", icon: Lock, category: "Security" },
  { id: "nav-policies", label: "Policies", href: "/admin/tool-policies", icon: Shield, category: "Security" },
  { id: "nav-approvals", label: "Approvals", href: "/admin/approvals", icon: ShieldCheck, category: "Security" },
  // -- Developer --
  { id: "nav-apikeys", label: "API Keys", href: "/admin/api-keys", icon: Key, category: "Developer" },
  { id: "nav-webhooks", label: "Webhooks", href: "/admin/webhooks", icon: Webhook, category: "Developer" },
  { id: "nav-apidocs", label: "API Docs", href: "/admin/api-docs", icon: FileCode, category: "Developer" },
  // -- Monitor --
  { id: "nav-usage", label: "Usage", href: "/admin/usage", icon: BarChart3, category: "Monitor" },
  { id: "nav-usage-overview", label: "Usage: Overview", hint: "Usage", href: "/admin/usage#Overview", icon: BarChart3, category: "Monitor" },
  { id: "nav-usage-forecast", label: "Usage: Forecast", hint: "Usage", href: "/admin/usage#Forecast", icon: BarChart3, category: "Monitor" },
  { id: "nav-usage-logs", label: "Usage: Logs", hint: "Usage", href: "/admin/usage#Logs", icon: BarChart3, category: "Monitor" },
  { id: "nav-usage-charts", label: "Usage: Charts", hint: "Usage", href: "/admin/usage#Charts", icon: BarChart3, category: "Monitor" },
  { id: "nav-usage-limits", label: "Usage: Limits", hint: "Usage", href: "/admin/usage#Limits", icon: BarChart3, category: "Monitor" },
  { id: "nav-usage-alerts", label: "Usage: Alerts", hint: "Usage", href: "/admin/usage#Alerts", icon: BarChart3, category: "Monitor" },
  { id: "nav-toolcalls", label: "Tool Calls", href: "/admin/tool-calls", icon: Activity, category: "Monitor" },
  { id: "nav-users", label: "Users", href: "/admin/users", icon: Users, category: "Monitor" },
  { id: "nav-logs", label: "Logs", href: "/admin/logs", icon: ScrollText, category: "Monitor" },
  { id: "nav-logs-traces", label: "Logs: Traces", hint: "Logs", href: "/admin/logs/traces", icon: ScrollText, category: "Monitor" },
  { id: "nav-logs-server", label: "Logs: Server", hint: "Logs", href: "/admin/logs/server", icon: ScrollText, category: "Monitor" },
  { id: "nav-logs-fallbacks", label: "Logs: Fallbacks", hint: "Logs", href: "/admin/logs/fallbacks", icon: ScrollText, category: "Monitor" },
  { id: "nav-diagnostics", label: "Diagnostics", href: "/admin/diagnostics", icon: HardDrive, category: "Monitor" },
  { id: "nav-config", label: "Config State", href: "/admin/config-state", icon: Code2, category: "Monitor" },
  { id: "nav-delegations", label: "Delegations", href: "/admin/delegations", icon: Users, category: "Monitor" },
  { id: "nav-memories", label: "Memories", href: "/admin/memories", icon: Brain, category: "Monitor" },
  { id: "nav-sandboxes", label: "Sandboxes", href: "/admin/sandboxes", icon: Boxes, category: "Monitor" },
  { id: "nav-sessions", label: "Sessions", href: "/admin/sessions", icon: MessageCircle, category: "Monitor" },
];

export const SETTINGS_ITEMS: PaletteItem[] = [
  { id: "nav-settings", label: "Settings", href: "/settings", icon: Settings, category: "Settings" },
  { id: "nav-settings-global", label: "Settings: Global", hint: "Settings", href: "/settings/system#Overview", icon: Settings, category: "Settings" },
  { id: "nav-settings-system", label: "Settings: System", hint: "Settings", href: "/settings/system#Overview", icon: Settings, category: "Settings" },
  { id: "nav-settings-paths", label: "Settings: Paths", hint: "Settings", href: "/settings/system#Operations", icon: Settings, category: "Settings" },
  { id: "nav-settings-general", label: "Settings: General", hint: "Settings", href: "/settings/system#Overview", icon: Settings, category: "Settings" },
  { id: "nav-settings-agent", label: "Settings: Agent", hint: "Settings", href: "/settings/system#Runtime%20%26%20Tools", icon: Settings, category: "Settings" },
  { id: "nav-settings-chat-history", label: "Settings: Chat History", hint: "Settings", href: "/settings/system#Memory%20%26%20Context", icon: Settings, category: "Settings" },
  { id: "nav-settings-embeddings", label: "Settings: Embeddings & RAG", hint: "Settings", href: "/settings/system#Retrieval", icon: Settings, category: "Settings" },
  { id: "nav-settings-reranking", label: "Settings: RAG Re-ranking", hint: "Settings", href: "/settings/system#Retrieval", icon: Settings, category: "Settings" },
  { id: "nav-settings-attachments", label: "Settings: Attachments", hint: "Settings", href: "/settings/system#Media%20%26%20Voice", icon: Settings, category: "Settings" },
  { id: "nav-settings-memory", label: "Settings: Memory & Learning", hint: "Settings", href: "/settings/system#Memory%20%26%20Context", icon: Settings, category: "Settings" },
  { id: "nav-settings-heartbeat", label: "Settings: Heartbeat", hint: "Settings", href: "/settings/system#Memory%20%26%20Context", icon: Settings, category: "Settings" },
  { id: "nav-settings-tool-summarization", label: "Settings: Tool Summarization", hint: "Settings", href: "/settings/system#Runtime%20%26%20Tools", icon: Settings, category: "Settings" },
  { id: "nav-settings-tool-policies", label: "Settings: Tool Policies", hint: "Settings", href: "/settings/system#Runtime%20%26%20Tools", icon: Settings, category: "Settings" },
  { id: "nav-settings-image-gen", label: "Settings: Image Generation", hint: "Settings", href: "/settings/system#Media%20%26%20Voice", icon: Settings, category: "Settings" },
  { id: "nav-settings-stt", label: "Settings: Speech-to-Text", hint: "Settings", href: "/settings/system#Media%20%26%20Voice", icon: Settings, category: "Settings" },
  { id: "nav-settings-prompt-gen", label: "Settings: Prompt Generation", hint: "Settings", href: "/settings/system#Media%20%26%20Voice", icon: Settings, category: "Settings" },
  { id: "nav-settings-docker", label: "Settings: Docker Stacks", hint: "Settings", href: "/settings/system#Runtime%20%26%20Tools", icon: Settings, category: "Settings" },
  { id: "nav-settings-rate-limiting", label: "Settings: API Rate Limiting", hint: "Settings", href: "/settings/system#Security%20%26%20Access", icon: Settings, category: "Settings" },
  { id: "nav-settings-security", label: "Settings: Security", hint: "Settings", href: "/settings/system#Security%20%26%20Access", icon: Settings, category: "Settings" },
  { id: "nav-settings-data-retention", label: "Settings: Data Retention", hint: "Settings", href: "/settings/system#Operations", icon: Settings, category: "Settings" },
  { id: "nav-settings-backup", label: "Settings: Backup", hint: "Settings", href: "/settings/system#Operations", icon: Settings, category: "Settings" },
];

export const CATEGORY_ORDER = [
  "Recent",
  "This Channel",
  "Channels",
  "Widgets",
  "Bots",
  "Configure",
  "Automate",
  "Security",
  "Developer",
  "Monitor",
  "Integrations",
  "Settings",
];

export function categoryRank(cat: string): number {
  const idx = CATEGORY_ORDER.indexOf(cat);
  return idx === -1 ? CATEGORY_ORDER.length : idx;
}
