"""BlueBubbles integration setup manifest."""

SETUP = {
    "icon": "MessageCircle",
    "env_vars": [
        {"key": "BLUEBUBBLES_SERVER_URL", "required": True, "description": "BlueBubbles server URL (e.g. http://192.168.1.50:1234)"},
        {"key": "BLUEBUBBLES_PASSWORD", "required": True, "description": "BlueBubbles server password", "secret": True},
        {"key": "AGENT_API_KEY", "required": True, "description": "API key for the agent server", "secret": True},
        {"key": "AGENT_BASE_URL", "required": False, "description": "Agent server URL (default: http://localhost:8000)"},
        {"key": "BB_DEFAULT_BOT", "required": False, "description": "Default bot ID for Socket.IO client (default: default). Not used by webhook path."},
        {"key": "BB_WAKE_WORDS", "required": False, "description": "Extra wake words (comma-separated). Added on top of automatic bot name/id wake words."},
        {"key": "BB_WEBHOOK_TOKEN", "required": False, "description": "Shared secret for webhook auth (?token=). If empty, webhook is unauthenticated.", "secret": True},
        {"key": "BB_SEND_METHOD", "required": False, "description": "iMessage send method: 'apple-script' (default, reliable) or 'private-api' (requires Private API helper)"},
        {"key": "BB_SUGGEST_CHATS", "required": False, "description": "Show recent chats dropdown when binding (default: true)"},
        {"key": "BB_SUGGEST_COUNT", "required": False, "description": "Number of recent chats to show in binding dropdown (default: 10, max: 50)"},
        {"key": "BB_SUGGEST_PREVIEW", "required": False, "description": "Show last message preview in binding dropdown (default: true)"},
        {"key": "BB_ECHO_SUPPRESS_WINDOW", "required": False, "description": "Seconds to suppress echo re-triggers after bot replies (default: 15). Prevents infinite loops when iMessage modifies bot text."},
    ],
    "api_permissions": "bluebubbles_integration",
    "webhook": {
        "path": "/integrations/bluebubbles/webhook",
        "description": "BlueBubbles new-message webhook receiver (optional ?token=BB_WEBHOOK_TOKEN auth)",
    },
    "instructions_url": None,
    "python_dependencies": [
        {"package": "python-socketio", "import_name": "socketio"},
        {"package": "aiohttp", "import_name": "aiohttp"},
    ],
    "debug_actions": [
        {
            "id": "pause",
            "label": "Pause Webhooks",
            "description": "Stop processing all incoming webhooks",
            "endpoint": "pause",
            "method": "POST",
            "style": "warning",
        },
        {
            "id": "resume",
            "label": "Resume Webhooks",
            "description": "Resume processing webhooks after a pause",
            "endpoint": "resume",
            "method": "POST",
            "style": "default",
        },
        {
            "id": "diagnose",
            "label": "Run Diagnostics",
            "description": "Check dispatcher, credentials, and channel bindings",
            "endpoint": "diagnose",
            "method": "GET",
        },
        {
            "id": "echo-state",
            "label": "Echo State",
            "description": "View per-chat echo detection state (cooldowns, circuit breaker, suppress window)",
            "endpoint": "echo-state",
            "method": "GET",
        },
    ],
    "activation": {
        "description": "iMessage relay via BlueBubbles — connection status and kill switch",
        "carapaces": [],
        "requires_workspace": False,
    },
    "chat_hud": [
        {
            "id": "bb-status",
            "style": "status_strip",
            "endpoint": "/hud/status",
            "poll_interval": 30,
            "label": "iMessage",
            "icon": "MessageCircle",
        },
        {
            "id": "bb-echo-diag",
            "style": "side_panel",
            "endpoint": "/hud/echo-diagnostics",
            "poll_interval": 10,
            "label": "Echo Diagnostics",
            "icon": "Activity",
            "collapsed_by_default": True,
            "width": 300,
        },
    ],
    "chat_hud_presets": {
        "default": {
            "label": "Connection Status",
            "description": "Shows iMessage connection state and pause/resume controls.",
            "widgets": ["bb-status"],
        },
        "diagnostics": {
            "label": "Diagnostics",
            "description": "Connection status plus a collapsible echo detection diagnostics panel showing per-chat cooldowns, circuit breakers, and suppress windows.",
            "widgets": ["bb-status", "bb-echo-diag"],
        },
        "none": {
            "label": "No HUD",
            "description": "Hide all BlueBubbles HUD widgets.",
            "widgets": [],
        },
    },
    "binding": {
        "client_id_prefix": "bb:",
        "client_id_placeholder": "bb:iMessage;-;+15551234567",
        "client_id_description": "BlueBubbles chat GUID (e.g. iMessage;-;+15551234567 for 1:1, iMessage;+;chat123 for group)",
        "display_name_placeholder": "+1 (555) 123-4567",
        "suggestions_endpoint": "/integrations/bluebubbles/binding-suggestions",
        "config_fields": [
            {"key": "extra_wake_words", "type": "string", "label": "Extra Wake Words", "description": "Comma-separated additional wake words for this chat", "default": ""},
            {"key": "use_bot_wake_word", "type": "boolean", "label": "Use Bot Name as Wake Word", "description": "Automatically use the channel bot's name and ID as wake words", "default": True},
            {"key": "echo_suppress_window", "type": "number", "label": "Echo Suppress Window (seconds)", "description": "Seconds to suppress echo re-triggers after bot replies. Increase for aggressive autocorrect. Leave empty for global default.", "default": ""},
            {"key": "send_method", "type": "select", "label": "Send Method", "description": "Override the global iMessage send method for this chat", "default": "", "options": [
                {"value": "", "label": "Use Global Default"},
                {"value": "apple-script", "label": "AppleScript (reliable)"},
                {"value": "private-api", "label": "Private API (requires helper)"},
            ]},
            {"key": "text_footer", "type": "string", "label": "Text Footer", "description": "Text appended to every outgoing message (e.g. ' - Michael Bot')", "default": ""},
            {"key": "typing_indicator", "type": "boolean", "label": "Typing Indicator", "description": "Show typing indicator in iMessage while the bot is processing", "default": True},
        ],
    },
}
