#!/usr/bin/env bash
# setup-e2e-instance.sh — Bootstrap a dedicated E2E Spindrel instance
#
# Designed to run ON the test server. Creates a separate Spindrel install
# with different ports so it doesn't conflict with the main instance.
#
# Usage:
#   bash scripts/setup-e2e-instance.sh [--install-dir /opt/spindrel-e2e]
#
# Environment variables (all optional, sane defaults provided):
#   E2E_INSTALL_DIR       Where to clone/update the repo (default: /opt/spindrel-e2e)
#   E2E_BRANCH            Git branch to track (default: development)
#   E2E_SERVER_PORT       Server port (default: 18000)
#   E2E_UI_PORT           UI port (default: 18081)
#   E2E_PG_PORT           Postgres port (default: 15432)
#   SPINDREL_PROVIDER     LLM provider ID (default: gemini)
#   SPINDREL_LLM_API_KEY  Provider API key (required for non-ollama providers)
#   SPINDREL_MODEL        Model name (default: per provider)
#   SPINDREL_API_KEY      Server API key (auto-generated if not set)

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

info()  { echo -e "${CYAN}$*${RESET}"; }
ok()    { echo -e "${GREEN}$*${RESET}"; }
err()   { echo -e "${RED}$*${RESET}" >&2; }
bold()  { echo -e "${BOLD}$*${RESET}"; }

# ── Configuration ──────────────────────────────────────────────────────────

INSTALL_DIR="${E2E_INSTALL_DIR:-/opt/spindrel-e2e}"
BRANCH="${E2E_BRANCH:-development}"
SERVER_PORT="${E2E_SERVER_PORT:-18000}"
UI_PORT="${E2E_UI_PORT:-18081}"
PG_PORT="${E2E_PG_PORT:-15432}"
REPO_URL="https://github.com/mtotho/spindrel.git"

# Parse --install-dir flag
while [[ $# -gt 0 ]]; do
    case $1 in
        --install-dir) INSTALL_DIR="$2"; shift 2 ;;
        *) err "Unknown option: $1"; exit 1 ;;
    esac
done

bold "  ┌─────────────────────────────────┐"
bold "  │   Spindrel E2E Instance Setup   │"
bold "  └─────────────────────────────────┘"
echo ""
info "Install dir:  $INSTALL_DIR"
info "Branch:       $BRANCH"
info "Ports:        server=$SERVER_PORT  ui=$UI_PORT  pg=$PG_PORT"
echo ""

# ── Clone or update repo ──────────────────────────────────────────────────

if [ -d "$INSTALL_DIR/.git" ]; then
    info "Updating existing repo..."
    cd "$INSTALL_DIR"
    git fetch origin
    git checkout "$BRANCH"
    git reset --hard "origin/$BRANCH"
else
    info "Cloning repo to $INSTALL_DIR..."
    sudo mkdir -p "$INSTALL_DIR"
    sudo chown "$(whoami):$(whoami)" "$INSTALL_DIR"
    git clone -b "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi
ok "Repo ready at $INSTALL_DIR (branch: $BRANCH)"

# ── Generate .env via headless setup ──────────────────────────────────────

export SPINDREL_HEADLESS=1
export SPINDREL_OVERWRITE=1
export SPINDREL_DEPLOY_MODE=docker
export SPINDREL_PROVIDER="${SPINDREL_PROVIDER:-gemini}"
export SPINDREL_WEB_SEARCH="${SPINDREL_WEB_SEARCH:-ddgs}"

# Forward any env vars already set
export SPINDREL_LLM_API_KEY="${SPINDREL_LLM_API_KEY:-}"
export SPINDREL_MODEL="${SPINDREL_MODEL:-}"
export SPINDREL_API_KEY="${SPINDREL_API_KEY:-}"

info "Running headless setup..."
python3 scripts/setup.py

ok ".env generated"

# ── Create docker-compose override for port remapping ─────────────────────

cat > docker-compose.override.yml <<EOF
# Auto-generated by setup-e2e-instance.sh — port overrides for E2E instance
name: "spindrel-e2e-instance"

services:
  agent-server:
    ports:
      - "${SERVER_PORT}:8000"
    environment:
      - LOG_LEVEL=WARNING
      - HEARTBEAT_ACTIVE_INTERVAL_MINUTES=9999
      - DOCKER_SANDBOX_ENABLED=false
      - DOCKER_STACKS_ENABLED=false
      - HOST_EXEC_ENABLED=false

  postgres:
    ports:
      - "${PG_PORT}:5432"

  ui:
    ports:
      - "${UI_PORT}:80"
EOF

ok "docker-compose.override.yml written (ports: $SERVER_PORT/$UI_PORT/$PG_PORT)"

# ── Build and start ──────────────────────────────────────────────────────

info "Building Docker images..."
docker compose build

info "Starting services..."
docker compose up -d

# ── Wait for healthy ─────────────────────────────────────────────────────

API_KEY=$(grep '^API_KEY=' .env | cut -d= -f2-)
info "Waiting for server to become healthy..."
for i in $(seq 1 30); do
    if curl -sf "http://localhost:${SERVER_PORT}/health" \
         -H "Authorization: Bearer ${API_KEY}" > /dev/null 2>&1; then
        ok "Server healthy at http://localhost:${SERVER_PORT}"
        break
    fi
    if [ "$i" -eq 30 ]; then
        err "Server did not become healthy after 30 attempts"
        docker compose logs --tail=50 agent-server
        exit 1
    fi
    sleep 2
done

# ── Summary ──────────────────────────────────────────────────────────────

echo ""
bold "  ┌─────────────────────────────────┐"
bold "  │      E2E Instance Ready!        │"
bold "  └─────────────────────────────────┘"
echo ""
echo "  Server:   http://localhost:${SERVER_PORT}"
echo "  UI:       http://localhost:${UI_PORT}"
echo "  Postgres: localhost:${PG_PORT}"
echo "  API Key:  ${API_KEY:0:20}..."
echo ""
echo "  Run E2E tests:"
echo "    E2E_MODE=external E2E_HOST=localhost E2E_PORT=${SERVER_PORT} E2E_API_KEY=\$API_KEY pytest tests/e2e/ -v"
echo ""
echo "  Update instance:"
echo "    cd $INSTALL_DIR && git pull && docker compose up -d --build"
echo ""
