#!/usr/bin/env python3
"""Spindrel interactive setup wizard.

Generates .env from user prompts. The Orchestrator bot (auto-seeded on first
boot) handles everything else — bot creation, integrations, workspace config.

Run via setup.sh or directly:
    python scripts/setup.py
"""
from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path

try:
    import questionary
    from questionary import Style
except ImportError:
    print("Error: questionary not installed. Run via setup.sh or: pip install questionary")
    sys.exit(1)

# ── Paths ───────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = REPO_ROOT / ".env"

# ── Style ───────────────────────────────────────────────────────────────────

STYLE = Style([
    ("qmark", "fg:cyan bold"),
    ("question", "bold"),
    ("answer", "fg:cyan"),
    ("pointer", "fg:cyan bold"),
    ("highlighted", "fg:cyan bold"),
    ("selected", "fg:cyan"),
])

# ── Provider presets ────────────────────────────────────────────────────────

PROVIDERS = {
    "LiteLLM proxy (self-hosted, most flexible)": {
        "ask": [
            ("LITELLM_BASE_URL", "LiteLLM base URL", "http://litellm:4000/v1"),
            ("LITELLM_API_KEY", "LiteLLM API key (if required)", ""),
        ],
        "models": [
            "gemini/gemini-2.5-flash",
            "gemini/gemini-2.5-pro",
            "claude-sonnet-4-5",
            "claude-opus-4",
            "gpt-4.1",
            "gpt-4.1-mini",
        ],
    },
    "OpenAI API": {
        "ask": [
            ("LITELLM_API_KEY", "OpenAI API key", ""),
        ],
        "set": {
            "LITELLM_BASE_URL": "https://api.openai.com/v1",
        },
        "models": [
            "gpt-4.1",
            "gpt-4.1-mini",
            "gpt-4.1-nano",
            "o3",
            "o4-mini",
        ],
    },
    # OpenRouter provides Claude, Gemini, Llama, etc. through one API key.
    # For direct Anthropic API, add a provider in Admin UI > Providers after setup.
    "OpenRouter (Anthropic, Google, Meta, etc.)": {
        "ask": [
            ("LITELLM_API_KEY", "OpenRouter API key", ""),
        ],
        "set": {
            "LITELLM_BASE_URL": "https://openrouter.ai/api/v1",
        },
        "models": [
            "anthropic/claude-sonnet-4-5",
            "anthropic/claude-opus-4",
            "google/gemini-2.5-flash",
            "meta-llama/llama-4-maverick",
        ],
    },
    "Google Gemini API": {
        "ask": [
            ("LITELLM_API_KEY", "Gemini API key", ""),
        ],
        "set": {
            "LITELLM_BASE_URL": "https://generativelanguage.googleapis.com/v1beta/openai/",
        },
        "models": [
            "gemini-2.5-flash",
            "gemini-2.5-pro",
        ],
    },
    "OpenAI-compatible (Ollama, vLLM, etc.)": {
        "ask": [
            ("LITELLM_BASE_URL", "API base URL", "http://localhost:11434/v1"),
            ("LITELLM_API_KEY", "API key (if required)", ""),
        ],
        "models": [],
    },
}


# ── Helpers ─────────────────────────────────────────────────────────────────

def generate_api_key() -> str:
    """Generate a random API key."""
    return f"ask_{secrets.token_urlsafe(32)}"


def write_env_file(config: dict[str, str]) -> None:
    """Write .env file from config dict."""
    lines: list[str] = []
    lines.append("# Generated by spindrel setup wizard")
    lines.append("")

    # Group settings logically
    sections = [
        ("Auth", ["API_KEY", "ADMIN_API_KEY"]),
        ("Database", ["DATABASE_URL"]),
        ("LLM Provider", ["LITELLM_BASE_URL", "LITELLM_API_KEY"]),
        ("Embeddings", ["EMBEDDING_MODEL", "EMBEDDING_DIMENSIONS"]),
        ("Web Search", ["WEB_SEARCH_MODE", "COMPOSE_PROFILES"]),
    ]

    written_keys: set[str] = set()
    for section_name, keys in sections:
        section_lines: list[str] = []
        for key in keys:
            if key in config and config[key]:
                section_lines.append(f"{key}={config[key]}")
                written_keys.add(key)
        if section_lines:
            lines.append(f"# {section_name}")
            lines.extend(section_lines)
            lines.append("")

    # Write remaining keys
    remaining = {k: v for k, v in config.items() if k not in written_keys and v}
    if remaining:
        lines.append("# Other")
        for key, val in sorted(remaining.items()):
            lines.append(f"{key}={val}")
        lines.append("")

    ENV_FILE.write_text("\n".join(lines) + "\n")


# ── Main wizard ─────────────────────────────────────────────────────────────

def main() -> None:
    print()

    # Check if .env already exists
    if ENV_FILE.exists():
        overwrite = questionary.confirm(
            ".env already exists. Overwrite it?",
            default=False,
            style=STYLE,
        ).ask()
        if not overwrite:
            print("Setup cancelled. Edit .env manually if needed.")
            return

    env_config: dict[str, str] = {}

    # ── 1. Deployment mode ──────────────────────────────────────────────────

    deploy = questionary.select(
        "Deployment mode:",
        choices=[
            questionary.Choice("Docker (recommended)", value="docker"),
            questionary.Choice("Local dev (uses dev-server.sh)", value="local"),
        ],
        style=STYLE,
    ).ask()
    if deploy is None:
        return

    if deploy == "docker":
        env_config["DATABASE_URL"] = "postgresql+asyncpg://agent:agent@postgres:5432/agentdb"
    else:
        db_url = questionary.text(
            "PostgreSQL URL:",
            default="postgresql+asyncpg://agent:agent@localhost:5432/agentdb",
            style=STYLE,
        ).ask()
        if db_url is None:
            return
        env_config["DATABASE_URL"] = db_url

    # ── 2. LLM Provider ────────────────────────────────────────────────────

    provider_name = questionary.select(
        "LLM Provider:",
        choices=list(PROVIDERS.keys()),
        style=STYLE,
    ).ask()
    if provider_name is None:
        return

    provider = PROVIDERS[provider_name]

    # Set fixed values
    for key, val in provider.get("set", {}).items():
        env_config[key] = val

    # Ask for configurable values
    for key, label, default in provider.get("ask", []):
        is_secret = "key" in label.lower() or "secret" in label.lower()
        val = questionary.password(
            f"{label}:",
            style=STYLE,
        ).ask() if is_secret and default == "" else questionary.text(
            f"{label}:",
            default=default,
            style=STYLE,
        ).ask()
        if val is None:
            return
        if val:
            env_config[key] = val

    # ── 3. Model selection ─────────────────────────────────────────────────

    model_choices = provider.get("models", [])
    if model_choices:
        model = questionary.select(
            "Default model (used by the Orchestrator bot):",
            choices=model_choices + [questionary.Choice("Enter custom model", value="__custom__")],
            style=STYLE,
        ).ask()
        if model is None:
            return
        if model == "__custom__":
            model = questionary.text("Model name:", style=STYLE).ask()
            if not model:
                return
    else:
        model = questionary.text(
            "Model name (e.g. llama3.1:latest):",
            style=STYLE,
        ).ask()
        if not model:
            return

    # Store the model for the orchestrator bot to pick up via config state
    env_config["DEFAULT_MODEL"] = model

    # ── 4. Web search ─────────────────────────────────────────────────────

    web_mode = questionary.select(
        "Web search backend:",
        choices=[
            questionary.Choice(
                "SearXNG — self-hosted, private (adds 2 containers)",
                value="searxng",
            ),
            questionary.Choice(
                "DuckDuckGo — lightweight, no extra containers",
                value="ddgs",
            ),
            questionary.Choice(
                "None — I'll add my own search tool",
                value="none",
            ),
        ],
        style=STYLE,
    ).ask()
    if web_mode is None:
        return

    env_config["WEB_SEARCH_MODE"] = web_mode
    if web_mode == "searxng":
        env_config["COMPOSE_PROFILES"] = "web-search"

    # ── 5. Auth ────────────────────────────────────────────────────────────

    generated_key = generate_api_key()
    auth_choice = questionary.select(
        "API authentication key:",
        choices=[
            questionary.Choice(f"Generate random key ({generated_key[:20]}...)", value="generate"),
            questionary.Choice("Enter my own key", value="custom"),
        ],
        style=STYLE,
    ).ask()
    if auth_choice is None:
        return

    if auth_choice == "generate":
        env_config["API_KEY"] = generated_key
    else:
        custom_key = questionary.password("API key:", style=STYLE).ask()
        if custom_key is None:
            return
        env_config["API_KEY"] = custom_key

    # ── Defaults ───────────────────────────────────────────────────────────

    env_config["EMBEDDING_MODEL"] = "text-embedding-3-small"
    env_config["EMBEDDING_DIMENSIONS"] = "1536"

    # ── Generate .env ──────────────────────────────────────────────────────

    print()
    print("\033[1m  Generating configuration...\033[0m")
    print()

    write_env_file(env_config)
    print(f"  \033[32m✓\033[0m .env")

    # ── Summary ────────────────────────────────────────────────────────────

    print()
    print("\033[1m  ┌─────────────────────────────────┐\033[0m")
    print("\033[1m  │         Setup Complete!          │\033[0m")
    print("\033[1m  └─────────────────────────────────┘\033[0m")
    print()
    print(f"  API Key: {env_config['API_KEY'][:20]}...")
    print(f"  Provider: {provider_name}")
    print(f"  Model: {model}")
    web_labels = {"searxng": "SearXNG (self-hosted)", "ddgs": "DuckDuckGo (lightweight)", "none": "Disabled"}
    print(f"  Web Search: {web_labels.get(web_mode, web_mode)}")
    print()
    print("  The Orchestrator bot will guide you through the rest:")
    print("  creating bots, enabling integrations, and configuring workspaces.")
    print()

    # ── Next steps ─────────────────────────────────────────────────────────

    if deploy == "docker":
        print("  \033[1mNext steps:\033[0m")
        print("  1. docker compose up -d")
        print("  2. Open http://localhost:8000")
        print("  3. The Orchestrator will greet you and walk you through setup.")
        print()

        start_now = questionary.confirm(
            "Start docker compose now?",
            default=True,
            style=STYLE,
        ).ask()
        if start_now:
            rc = os.system("docker compose up -d")
            if rc != 0:
                print(f"\n  \033[31mDocker compose failed (exit {rc}). Start manually: docker compose up -d\033[0m")
    else:
        print("  \033[1mNext steps:\033[0m")
        print("  1. bash scripts/dev-server.sh")
        print("  2. Open http://localhost:8000")
        print("  3. The Orchestrator will greet you and walk you through setup.")
        print()

        start_now = questionary.confirm(
            "Start dev server now?",
            default=False,
            style=STYLE,
        ).ask()
        if start_now:
            os.execvp("bash", ["bash", str(REPO_ROOT / "scripts" / "dev-server.sh")])


if __name__ == "__main__":
    main()
