#!/usr/bin/env python3
"""Spindrel interactive setup wizard.

Generates .env from user prompts and a provider-seed.yaml for first-boot
DB seeding.  The Orchestrator bot (auto-seeded on first boot) handles
everything else — bot creation, integrations, workspace config.

Run via setup.sh or directly:
    python scripts/setup.py
"""
from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path

try:
    import questionary
    from questionary import Style
except ImportError:
    print("Error: questionary not installed. Run via setup.sh or: pip install questionary")
    sys.exit(1)

try:
    import yaml
except ImportError:
    print("Error: pyyaml not installed. Run via setup.sh or: pip install pyyaml")
    sys.exit(1)

# ── Paths ───────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = REPO_ROOT / ".env"
SEED_FILE = REPO_ROOT / "provider-seed.yaml"

# ── Style ───────────────────────────────────────────────────────────────────

STYLE = Style([
    ("qmark", "fg:cyan bold"),
    ("question", "bold"),
    ("answer", "fg:cyan"),
    ("pointer", "fg:cyan bold"),
    ("highlighted", "fg:cyan bold"),
    ("selected", "fg:cyan"),
])

# ── Typed provider presets ──────────────────────────────────────────────────

PROVIDERS = [
    {
        "label": "Ollama (local, no API key)",
        "id": "ollama",
        "provider_type": "ollama",
        "base_url_default": "http://localhost:11434",
        "base_url_docker": "http://host.docker.internal:11434",
        "ask_base_url": True,
        "ask_api_key": False,
        "models": [],  # free-text input
    },
    {
        "label": "OpenAI",
        "id": "openai",
        "provider_type": "openai",
        "base_url": "https://api.openai.com/v1",
        "ask_base_url": False,
        "ask_api_key": True,
        "models": ["gpt-4.1", "gpt-4.1-mini", "o3", "o4-mini"],
    },
    {
        "label": "Anthropic",
        "id": "anthropic",
        "provider_type": "anthropic",
        "base_url": "https://api.anthropic.com",
        "ask_base_url": False,
        "ask_api_key": True,
        "models": ["claude-sonnet-4-5", "claude-opus-4"],
    },
    {
        "label": "Google Gemini",
        "id": "gemini",
        "provider_type": "openai-compatible",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai/",
        "ask_base_url": False,
        "ask_api_key": True,
        "models": ["gemini-2.5-flash", "gemini-2.5-pro"],
    },
    {
        "label": "OpenRouter (Anthropic, Google, Meta, etc.)",
        "id": "openrouter",
        "provider_type": "openai-compatible",
        "base_url": "https://openrouter.ai/api/v1",
        "ask_base_url": False,
        "ask_api_key": True,
        "models": ["anthropic/claude-sonnet-4-5", "google/gemini-2.5-flash"],
    },
    {
        "label": "LiteLLM proxy (self-hosted)",
        "id": "litellm",
        "provider_type": "litellm",
        "base_url_default": "http://litellm:4000/v1",
        "ask_base_url": True,
        "ask_api_key": "optional",  # optional — may not need a key
        "models": [
            "gemini/gemini-2.5-flash",
            "claude-sonnet-4-5",
            "gpt-4.1",
        ],
    },
    {
        "label": "Other OpenAI-compatible endpoint",
        "id": "custom",
        "provider_type": "openai-compatible",
        "base_url_default": "http://localhost:8080/v1",
        "ask_base_url": True,
        "ask_api_key": "optional",
        "models": [],  # free-text input
    },
]


# ── Helpers ─────────────────────────────────────────────────────────────────

def generate_api_key() -> str:
    """Generate a random API key."""
    return f"ask_{secrets.token_urlsafe(32)}"


def write_env_file(config: dict[str, str]) -> None:
    """Write .env file from config dict."""
    lines: list[str] = []
    lines.append("# Generated by spindrel setup wizard")
    lines.append("")

    # Group settings logically
    sections = [
        ("Auth", ["API_KEY", "ADMIN_API_KEY"]),
        ("Database", ["DATABASE_URL"]),
        ("Default Model", ["DEFAULT_MODEL"]),
        ("Web Search", ["WEB_SEARCH_MODE", "SEARXNG_URL", "PLAYWRIGHT_WS_URL", "COMPOSE_PROFILES"]),
    ]

    written_keys: set[str] = set()
    for section_name, keys in sections:
        section_lines: list[str] = []
        for key in keys:
            if key in config and config[key]:
                section_lines.append(f"{key}={config[key]}")
                written_keys.add(key)
        if section_lines:
            lines.append(f"# {section_name}")
            lines.extend(section_lines)
            lines.append("")

    # Write remaining keys
    remaining = {k: v for k, v in config.items() if k not in written_keys and v}
    if remaining:
        lines.append("# Other")
        for key, val in sorted(remaining.items()):
            lines.append(f"{key}={val}")
        lines.append("")

    ENV_FILE.write_text("\n".join(lines) + "\n")


def write_seed_file(provider: dict, base_url: str, api_key: str) -> None:
    """Write provider-seed.yaml for server first-boot consumption."""
    seed = {
        "id": provider["id"],
        "provider_type": provider["provider_type"],
        "display_name": provider["label"],
        "base_url": base_url,
        "api_key": api_key,
    }
    SEED_FILE.write_text(
        "# Auto-generated by setup wizard. Server consumes this on first boot.\n"
        + yaml.dump(seed, default_flow_style=False, sort_keys=False)
    )


# ── Main wizard ─────────────────────────────────────────────────────────────

def main() -> None:
    print()

    # Check if .env already exists
    if ENV_FILE.exists():
        overwrite = questionary.confirm(
            ".env already exists. Overwrite it?",
            default=False,
            style=STYLE,
        ).ask()
        if not overwrite:
            print("Setup cancelled. Edit .env manually if needed.")
            return

    env_config: dict[str, str] = {}

    # ── 1. Deployment mode ──────────────────────────────────────────────────

    deploy = questionary.select(
        "Deployment mode:",
        choices=[
            questionary.Choice("Docker (recommended)", value="docker"),
            questionary.Choice("Local dev (uses dev-server.sh)", value="local"),
        ],
        style=STYLE,
    ).ask()
    if deploy is None:
        return

    if deploy == "docker":
        env_config["DATABASE_URL"] = "postgresql+asyncpg://agent:agent@postgres:5432/agentdb"
    else:
        db_url = questionary.text(
            "PostgreSQL URL:",
            default="postgresql+asyncpg://agent:agent@localhost:5432/agentdb",
            style=STYLE,
        ).ask()
        if db_url is None:
            return
        env_config["DATABASE_URL"] = db_url

    # ── 2. LLM Provider ────────────────────────────────────────────────────

    provider_choices = [
        questionary.Choice(p["label"], value=i) for i, p in enumerate(PROVIDERS)
    ] + [questionary.Choice("Skip — configure in UI later", value="skip")]

    provider_idx = questionary.select(
        "LLM Provider:",
        choices=provider_choices,
        style=STYLE,
    ).ask()
    if provider_idx is None:
        return

    provider_name_label = "None (configure later)"
    model = ""
    seed_written = False

    if provider_idx != "skip":
        provider = PROVIDERS[provider_idx]
        provider_name_label = provider["label"]

        # Ask for base URL if needed
        if provider.get("ask_base_url"):
            # Use Docker-aware default when available
            if deploy == "docker" and "base_url_docker" in provider:
                default_url = provider["base_url_docker"]
                print()
                print("  \033[33m⚠\033[0m  Docker can't reach localhost on your host machine.")
                print(f"     Use \033[1mhost.docker.internal\033[0m instead of localhost.")
                print(f"     Default below is already set correctly.")
                print()
            else:
                default_url = provider.get("base_url_default", "")
            base_url = questionary.text(
                "Base URL:",
                default=default_url,
                style=STYLE,
            ).ask()
            if base_url is None:
                return
        else:
            base_url = provider.get("base_url", "")

        # Ask for API key if needed
        api_key = ""
        if provider.get("ask_api_key") is True:
            # Required key
            api_key = questionary.password(
                "API key:",
                style=STYLE,
            ).ask()
            if api_key is None:
                return
            if not api_key:
                print("  \033[33m⚠\033[0m  API key is required for this provider.")
                return
        elif provider.get("ask_api_key") == "optional":
            api_key = questionary.password(
                "API key (leave empty if not required):",
                style=STYLE,
            ).ask()
            if api_key is None:
                return

        # ── 3. Model selection ─────────────────────────────────────────────

        model_choices = provider.get("models", [])
        if model_choices:
            model = questionary.select(
                "Default model:",
                choices=model_choices + [questionary.Choice("Enter custom model", value="__custom__")],
                style=STYLE,
            ).ask()
            if model is None:
                return
            if model == "__custom__":
                model = questionary.text("Model name:", style=STYLE).ask()
                if not model:
                    return
        else:
            example = "gemma4:e4b" if provider["provider_type"] == "ollama" else "model-name"
            model = questionary.text(
                f"Model name (e.g. {example}):",
                style=STYLE,
            ).ask()
            if not model:
                return

        env_config["DEFAULT_MODEL"] = model

        # Write seed file
        write_seed_file(provider, base_url, api_key)
        seed_written = True
    else:
        # Skip: no seed file, no DEFAULT_MODEL
        pass

    # ── 4. Web search ─────────────────────────────────────────────────────

    web_mode = questionary.select(
        "Web search backend:",
        choices=[
            questionary.Choice(
                "SearXNG — built-in containers (adds 2 containers)",
                value="searxng",
            ),
            questionary.Choice(
                "SearXNG — external (bring your own instance)",
                value="searxng-external",
            ),
            questionary.Choice(
                "DuckDuckGo — lightweight, no extra containers",
                value="ddgs",
            ),
            questionary.Choice(
                "None — I'll add my own search tool",
                value="none",
            ),
        ],
        style=STYLE,
    ).ask()
    if web_mode is None:
        return

    if web_mode == "searxng":
        env_config["WEB_SEARCH_MODE"] = "searxng"
        env_config["COMPOSE_PROFILES"] = "web-search"
    elif web_mode == "searxng-external":
        env_config["WEB_SEARCH_MODE"] = "searxng"
        searxng_url = questionary.text(
            "SearXNG URL:",
            default="http://localhost:8080",
            style=STYLE,
        ).ask()
        if searxng_url is None:
            return
        env_config["SEARXNG_URL"] = searxng_url
        playwright_url = questionary.text(
            "Playwright WebSocket URL (leave empty to skip JS rendering):",
            default="",
            style=STYLE,
        ).ask()
        if playwright_url is None:
            return
        if playwright_url:
            env_config["PLAYWRIGHT_WS_URL"] = playwright_url
    else:
        env_config["WEB_SEARCH_MODE"] = web_mode

    # ── 5. Auth ────────────────────────────────────────────────────────────

    generated_key = generate_api_key()
    auth_choice = questionary.select(
        "API authentication key:",
        choices=[
            questionary.Choice(f"Generate random key ({generated_key[:20]}...)", value="generate"),
            questionary.Choice("Enter my own key", value="custom"),
        ],
        style=STYLE,
    ).ask()
    if auth_choice is None:
        return

    if auth_choice == "generate":
        env_config["API_KEY"] = generated_key
    else:
        custom_key = questionary.password("API key:", style=STYLE).ask()
        if custom_key is None:
            return
        env_config["API_KEY"] = custom_key

    # ── Generate .env ──────────────────────────────────────────────────────

    print()
    print("\033[1m  Generating configuration...\033[0m")
    print()

    write_env_file(env_config)
    print(f"  \033[32m✓\033[0m .env")
    if seed_written:
        print(f"  \033[32m✓\033[0m provider-seed.yaml (consumed on first server boot)")

    # ── Summary ────────────────────────────────────────────────────────────

    print()
    print("\033[1m  ┌─────────────────────────────────┐\033[0m")
    print("\033[1m  │         Setup Complete!          │\033[0m")
    print("\033[1m  └─────────────────────────────────┘\033[0m")
    print()
    print(f"  API Key: {env_config['API_KEY'][:20]}...")
    print(f"  Provider: {provider_name_label}")
    if model:
        print(f"  Model: {model}")
    web_labels = {"searxng": "SearXNG (built-in)", "searxng-external": "SearXNG (external)", "ddgs": "DuckDuckGo (lightweight)", "none": "Disabled"}
    print(f"  Web Search: {web_labels.get(web_mode, web_mode)}")
    print()
    print("  The Orchestrator bot will guide you through the rest:")
    print("  creating bots, enabling integrations, and configuring workspaces.")
    print()

    # ── Next steps ─────────────────────────────────────────────────────────

    if deploy == "docker":
        print("  \033[1mNext steps:\033[0m")
        print("  1. docker compose up -d")
        print("  2. Open http://localhost:8000")
        print("  3. The Orchestrator will greet you and walk you through setup.")
        print()

        start_now = questionary.confirm(
            "Start docker compose now?",
            default=True,
            style=STYLE,
        ).ask()
        if start_now:
            rc = os.system("docker compose up -d")
            if rc != 0:
                print(f"\n  \033[31mDocker compose failed (exit {rc}). Start manually: docker compose up -d\033[0m")
            else:
                print()
                if SEED_FILE.exists():
                    print(f"  \033[2mprovider-seed.yaml will be consumed on first server boot\033[0m")
                print(f"  \033[32m✓\033[0m Server running at \033[1mhttp://localhost:8000\033[0m")
                print(f"  \033[32m✓\033[0m UI hosted at     \033[1mhttp://localhost:8081\033[0m")
                print()
    else:
        print("  \033[1mNext steps:\033[0m")
        print("  1. bash scripts/dev-server.sh")
        print("  2. Open http://localhost:8000")
        print("  3. The Orchestrator will greet you and walk you through setup.")
        print()

        start_now = questionary.confirm(
            "Start dev server now?",
            default=False,
            style=STYLE,
        ).ask()
        if start_now:
            os.execvp("bash", ["bash", str(REPO_ROOT / "scripts" / "dev-server.sh")])


if __name__ == "__main__":
    main()
