"""Tests for attachment-to-message linking via pre-allocated user message ID."""

import uuid
from unittest.mock import AsyncMock, MagicMock, patch

import pytest


@pytest.mark.asyncio
async def test_persist_user_message_uses_pre_allocated_id():
    """When pre_allocated_id is set, the message row should use that UUID."""
    from app.services.turn_worker import _persist_and_publish_user_message

    pre_id = uuid.uuid4()
    session_id = uuid.uuid4()
    channel_id = uuid.uuid4()
    correlation_id = uuid.uuid4()

    captured_row = {}

    class FakeDB:
        async def commit(self):
            pass

        async def refresh(self, row):
            row.id = pre_id
            row.created_at = "2026-04-15T00:00:00Z"

        def add(self, row):
            captured_row["id"] = row.id
            captured_row["role"] = row.role

    class FakeCtx:
        async def __aenter__(self):
            return FakeDB()

        async def __aexit__(self, *a):
            pass

    with (
        patch("app.services.turn_worker.async_session", return_value=FakeCtx()),
        patch("app.services.turn_worker.publish_typed"),
        patch("app.services.outbox_publish.enqueue_new_message_for_channel", new_callable=AsyncMock),
    ):
        result = await _persist_and_publish_user_message(
            session_id=session_id,
            channel_id=channel_id,
            text="hello",
            correlation_id=correlation_id,
            metadata={},
            pre_allocated_id=pre_id,
        )

    assert captured_row["id"] == pre_id
    assert result == pre_id


@pytest.mark.asyncio
async def test_persist_user_message_auto_generates_id_without_pre_allocation():
    """Without pre_allocated_id, the message should auto-generate a UUID."""
    from app.services.turn_worker import _persist_and_publish_user_message

    session_id = uuid.uuid4()
    channel_id = uuid.uuid4()
    correlation_id = uuid.uuid4()

    captured_row = {}

    class FakeDB:
        async def commit(self):
            pass

        async def refresh(self, row):
            if not hasattr(row, "id") or row.id is None:
                row.id = uuid.uuid4()
            row.created_at = "2026-04-15T00:00:00Z"

        def add(self, row):
            captured_row["has_explicit_id"] = hasattr(row, "_sa_instance_state") or "id" in row.__dict__

    class FakeCtx:
        async def __aenter__(self):
            return FakeDB()

        async def __aexit__(self, *a):
            pass

    with (
        patch("app.services.turn_worker.async_session", return_value=FakeCtx()),
        patch("app.services.turn_worker.publish_typed"),
        patch("app.services.outbox_publish.enqueue_new_message_for_channel", new_callable=AsyncMock),
    ):
        result = await _persist_and_publish_user_message(
            session_id=session_id,
            channel_id=channel_id,
            text="hello",
            correlation_id=correlation_id,
            metadata={},
        )

    # Should still return a valid UUID (auto-generated by DB)
    assert result is not None
